inputs:
  my_name:
    required: true
  release_version:
    required: false
    default: ''

outputs:
  app:
    description: "app name"
    value: ${{ }}
  image:
    description: "image to be build on"
    value: ${{}}
  maven_script:
    description: "application runnable command"
    value: ${{steps.outputs.echoMyName}}

name:
description:
runs:
  using: "composite"
  steps:
    - name: checkout code
      uses: actions/checkout@v4    
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Echo my name
      id: echoMyName
      run: |
        echo "${{inputs.my_name}}"
        myTag = config.myTag
        dockerFile = config.docker_file_path
        echo "myTag" >>GITHUB.OUTPUTS
        echo "dockerFile" >> GITHUB.OUTPUTS
      shell: bash