name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      my_name:
         required: false
         type: string
         default: 'neha'


jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          branch: master

      
      - name: Log in to Jfrog
        run: |
           echo "${{ secrets.JFROG_PASSWORD }}" | \
           docker login ${{ secrets.JFROG_REGISTRY }} -u "${{ secrets.JFROG_USERNAME }}" --password-stdin
       

      - name: Build  docker image
        id: build
        run: |
          echo " building docker image"
          docker image build \
          --build-arg MAVEN_OPTS="-Xmx1024m" \
          --build-arg APP_ENV="dev" \
          -t ${{ secrets.JFROG_REGISTRY}}/${{ secrets.JFROG_REPO}}/my-image:latest \
          .
      
      - name: Push docker image
        run: |
          docker push ${{ secrets.JFROG_REGISTRY}}/${{ secrets.JFROG_REPO}}/my-image:latest

        
  deployDev:
    runs-on: ubuntu-latest
    needs: [ build ]
    environment: feature-dev
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to JFrog Docker registry
        run: echo "${{ secrets.JFROG_PASSWORD }}" | docker login trialx1vkqp.jfrog.io -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      - name: Pull Docker image from JFrog
        run: docker pull trialx1vkqp.jfrog.io/mydocker-docker-local/my-image:latest

      - name: Run container in environment
        run: |
          docker run -d \
            -p 8080:8080 \  # map ports (adjust as needed)
            --name my-app \
            trialx1vkqp.jfrog.io/mydocker-docker-local/my-image:latest
  
  # deployStg:
  #   runs-on: ubuntu-latest
  #   needs: [ deployDev ]
     

