name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      my_name:
         required: false
         type: string
         default: 'neha'


jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          branch: master

      
      - name: Log in to Jfrog
        run: |
           echo "${{ secrets.JFROG_PASSWORD }}" | \
           docker login ${{ secrets.JFROG_REGISTRY }} -u "${{ secrets.JFROG_USERNAME }}" --password-stdin
       

      - name: Build  docker image
        id: build
        run: |
          echo " building docker image"
          docker image build \
          --build-arg IMAGE=maven:3.9.9-eclipse-temurin-17 \
          --build-arg MAVEN_OPTS="-Xmx1024m" \
          --build-arg APP_ENV="dev" \
          -t ${{ secrets.JFROG_REGISTRY}}/${{ secrets.JFROG_REPO}}/my-image:latest \
          .
      
      - name: Push docker image
        run: |
          docker push ${{ secrets.JFROG_REGISTRY}}/${{ secrets.JFROG_REPO}}/my-image:latest
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [ build ]
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         ref: test

  #     - name: Run Unit Tests
  #       run: mvn test
        
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [ build, test ]
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         ref: test
      
  #     - name: Run My program
  #       run: |
  #         echo "Deploying my application"
  #     - name: Log in to Docker Hub
  #       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
  #     - name: Build Docker image
  #       run: docker build -t mydockerhubusername/my-app:latest .

  #     - name: Push Docker image
  #       run: docker push mydockerhubusername/my-app:latest

  #     - name: Pull Docker image
  #       run: docker pull mydockerhubusername/my-app:latest

  #     - name: Run Docker container
  #       run: docker run --rm mydockerhubusername/my-app:latest 
  #       continue-on-error: true  

