name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      my_name:
         required: false
         type: string
         default: 'neha'

jobs:
  init:
    name: Initialize
    runs-on: [mmc-ubuntu]
    steps:
      - name: init
        id: init
        uses: anuragsha14/myWorkflowRepo1/initialize@main
        with:
          my_name: 'anvay'
      

  build:
    runs-on: ubuntu-latest
    needs: [ init ]
    steps: 
      - name: checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: test
          path: my_folder

      # - name: Build my app
      #   run: mvn -B clean package

      - name: Build  docker image
        id: build
        run: |
          echo " building docker image"
          docker image build \
          -f ./docker/Dockerfile \
          --build-arg IMAGE="${{ needs.init.outputs.image }}"
          --build-arg MAVEN_SCRIPT="${{ needs.init.outputs.maven_script }}"
          --build-arg CHECKOUT_DIR="${{ steps.checkout.outputs.path }}"
          -t my-image:12345
          . 
          docker push ${{ my-image:12345 }}
      
      

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Run Unit Tests
        run: mvn test
        
  deploy:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: test
      
      - name: Run My program
        run: |
          echo "Deploying my application"
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t mydockerhubusername/my-app:latest .

      - name: Push Docker image
        run: docker push mydockerhubusername/my-app:latest

      - name: Pull Docker image
        run: docker pull mydockerhubusername/my-app:latest

      - name: Run Docker container
        run: docker run --rm mydockerhubusername/my-app:latest 
        continue-on-error: true  

